SELECT USER
FROM DUAL;
--==>> SCOTT


--○ 기존 테이블 삭제
DROP TABLE TBL_MEMBER;
--==>> Table TBL_MEMBER이(가) 삭제되었습니다.

--○ 테이블 생성
CREATE TABLE TBL_MEMBER
( SID   NUMBER
, NAME  VARCHAR2(30) NOT NULL
, TEL   VARCHAR2(40)
, CONSTRAINT MEMBER_SID_PK PRIMARY KEY(SID)
);
--==>> Table TBL_MEMBER이(가) 생성되었습니다.

--○ 기존 시퀀스 제거
DROP SEQUENCE MEMBERSEQ;

--  시퀀스 생성
CREATE SEQUENCE MEMBERSEQ
NOCACHE;
--==>> Sequence MEMBERSEQ이(가) 생성되었습니다.

--○ 샘플 데이터 입력 (TBL_MEMBER)
INSERT INTO TBL_MEMBER (SID, NAME, TEL) VALUES (MEMBERSEQ.NEXTVAL , '노은하', '010-1111-1111');
INSERT INTO TBL_MEMBER (SID, NAME, TEL) VALUES (MEMBERSEQ.NEXTVAL , '박가영', '010-2222-2222');
INSERT INTO TBL_MEMBER (SID, NAME, TEL) VALUES (MEMBERSEQ.NEXTVAL , '채다선', '010-3333-3333');
INSERT INTO TBL_MEMBER (SID, NAME, TEL) VALUES (MEMBERSEQ.NEXTVAL , '김수환', '010-4444-4444');
INSERT INTO TBL_MEMBER (SID, NAME, TEL) VALUES (MEMBERSEQ.NEXTVAL , '김다슬', '010-5555-5555');

-- 전체 조회
SELECT SID, NAME, TEL
FROM TBL_MEMBER
ORDER BY SID;
--> 한줄 구성
SELECT SID, NAME, TEL FROM TBL_MEMBER ORDER BY SID
;

-- 인원수 카운트 
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBER;

SELECT COUNT(*) AS COUNT FROM TBL_MEMBER
;

-- 커밋
COMMIT;


-- 회원 정보 점색
SELECT SID, NAME, TEL
FROM TBL_MEMBER
WHERE SID = 1;
--> 한줄 구성
SELECT SID, NAME, TEL FROM TBL_MEMBER WHERE SID = 1
;

-- 회원 정보 수정
UPDATE TBL_MEMBER
SET NAME = '김민지' , TEL = '010-6666-6666' 
WHERE SID = 6;
--> 한줄 구성
UPDATE TBL_MEMBER SET NAME = '김민지' , TEL = '010-6666-6666' WHERE SID = 6
;
ROLLBACK;

-- 회원 정보 삭제 해야됨!!
DELETE
FROM TBL_MEMBER
WHERE SID = 1;

ROLLBACK;

-- 기존 테이블 제거
DROP TABLE TBL_SCORE;

-- 테이블 생성
CREATE TABLE TBL_MEMBERSCORE
( SID   NUMBER
, KOR   NUMBER(3)
, ENG   NUMBER(3)
, MAT   NUMBER(3)
, CONSTRAINT MEMBERSCORE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT MEMBERSCORE_KOR_CK CHECK(KOR BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_ENG_CK CHECK(ENG BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_MAT_CK CHECK(MAT BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_SID_FK FOREIGN KEY(SID)
             REFERENCES TBL_MEMBER(SID)
);

-- 샘플 데이터 입력
INSERT INTO TBL_MEMBERSCORE(SID, KOR, ENG, MAT) VALUES (1, 90, 80, 70);
INSERT INTO TBL_MEMBERSCORE(SID, KOR, ENG, MAT) VALUES (2, 80, 70, 60);

-- 확인
SELECT SID, KOR, ENG, MAT
FROM TBL_MEMBERSCORE
ORDER BY SID;
--> 한줄 구성
SELECT SID, KOR, ENG, MAT FROM TBL_MEMBERSCORE ORDER BY SID
;
--==>>
/*
1	90	80	70
2	80	70	60
*/

-- 커밋
COMMIT;

-- 입력된 성적 데이터의 개수 확인 
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERSCORE;
--> 한줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERSCORE
;

--○ 성적 데이터 수정
UPDATE TBL_MEMBERSCORE
SET KOR = 91, ENG= 81, MAT = 71
WHERE SID = 1;
--> 한줄 구성
UPDATE TBL_MEMBERSCORE SET KOR = 91, ENG= 81, MAT = 71 WHERE SID = 1
;
--==>> 1 행 이(가) 업데이트되었습니다.

-- 확인
SELECT *
FROM TBL_MEMBERSCORE;
--==>>
/*
1	91	81	71
2	80	70	60
*/

--○ 커밋
COMMIT;
--==> 커밋 완료.

--○ 성적 데이터 삭제
DELETE
FROM TBL_MEMBERSCORE
WHERE SID = 1;
--=>> 1 행 이(가) 삭제되었습니다.
-- 한줄 구성
DELETE FROM TBL_MEMBERSCORE WHERE SID = 1
;

-- 롤백
ROLLBACK;
--==>> 롤백 완료.

--○ 전체 리스트 조회 쿼리문 구성
SELECT M.SID, M.NAME, M.TEL
     , S.KOR, S.ENG , S.MAT
FROM TBL_MEMBER M , TBL_MEMBERSCORE S
WHERE M.SID = S.SID;
--==>>
/*
1	노은하	010-1111-1111	91	81	71
2	박가영	010-2222-2222	80	70	60
*/

--○ 전체 리스트 조회 쿼리문 구성 개선 → LEFT JOIN
SELECT M.SID, M.NAME, M.TEL
     , S.KOR, S.ENG , S.MAT
FROM TBL_MEMBER M , TBL_MEMBERSCORE S
WHERE M.SID = S.SID(+);
--==>>
/*
노은하	010-1111-1111	 91	     81  	 71
박가영	010-2222-2222	 80	     70  	 60
채다선	010-3333-3333	(null)  (null)  (null)		
김수환	010-4444-4444	(null)	(null)	(null)
김다슬	010-5555-5555	(null)	(null)	(null)
*/

--○ 전체 리스트 조회 쿼리문 구성 개선 → LEFT JOIN → 개선 NVL()
SELECT M.SID, M.NAME, M.TEL
     ,NVL(S.KOR, -1)
     ,NVL(S.ENG, -1)
     ,NVL(S.MAT, -1)
FROM TBL_MEMBER M , TBL_MEMBERSCORE S
WHERE M.SID = S.SID(+);
--==>>
/*
1	노은하	010-1111-1111	91	81	71
2	박가영	010-2222-2222	80	70	60
3	채다선	010-3333-3333	-1	-1	-1
4	김수환	010-4444-4444	-1	-1	-1
5	김다슬	010-5555-5555	-1	-1	-1
*/

--○ 전체 리스트 조회 전용 뷰 생성
CREATE OR REPLACE VIEW VIEW_MEMBERSCORE
AS
SELECT M.SID, M.NAME, M.TEL
     ,NVL(S.KOR, -1) AS KOR 
     ,NVL(S.ENG, -1) AS ENG
     ,NVL(S.MAT, -1) AS MAT
FROM TBL_MEMBER M , TBL_MEMBERSCORE S
WHERE M.SID = S.SID(+);
--==>> View VIEW_MEMBERSCORE이(가) 생성되었습니다.

--○ 생성한 뷰를 활용한 리스트 조회
SELECT SID, NAME, KOR, ENG, MAT
      ,(KOR+ENG+MAT) AS TOT
      ,(KOR+ENG+MAT)/3 AS AVG
      , RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) AS RANK
FROM VIEW_MEMBERSCORE
ORDER BY SID;
--> 한줄 구성
SELECT SID, NAME, KOR, ENG, MAT,(KOR+ENG+MAT) AS TOT,(KOR+ENG+MAT)/3 AS AVG, RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) AS RANK FROM VIEW_MEMBERSCORE ORDER BY SID
;
--==>>
/*
1	노은하	91	81	71	243	81	1
2	박가영	80	70	60	210	70	2
3	채다선	-1	-1	-1	-3	-1	3
4	김수환	-1	-1	-1	-3	-1	3
5	김다슬	-1	-1	-1	-3	-1	3
*/

-- 생성한 뷰를 활용한 번호 검색
SELECT SID,NAME, KOR, MAT
FROM VIEW_MEMBERSCORE
WHERE SID = 1;
--> 한줄구성
SELECT SID,NAME,KOR, ENG,MAT FROM VIEW_MEMBERSCORE WHERE SID = 1
;

--○ 참조 데이터 레코드 수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERSCORE
WHERE SID = 1;
--> 한줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERSCORE WHERE SID = 1
;

