
SELECT USER
FROM DUAL;
--==>> HR

--■■■ 팀 별 실습 수행 과제 ■■■--

-- 제출 파일명
-- ·20231031_03_hr(2팀_최혜인).sql
-- ·20231031_03_hr(2팀_최혜인) 수행후기.txt

-- HR 샘플스키마 ERD 를 이용한 테이블 재구성~!!! 

-- 팀별로... HR 샘플스키마에 있는 기본 테이블(7개)
-- COUNTRIES / DEPARTMENTS / EMPLOYEES / JOBS ○ / JOB_HISTORY / LOCATIONS / REGIONS
-- 을 똑~~~~~~ 같이 새로 구성한다.

-- 단, 생성하는 테이블의 이름은 『테이블명+팀번호』
-- COUNTRIES2 / DEPARTMENTS2 / EMPLOYEES2 / JOBS2 / JOB_HISTORY2 / LOCATIONS2 / REGIONS2

-- 1. 기존 대상 테이블들의 정보 수집
-- 2. 테이블 생성(컬럼이름, 자료형, DEFAULT표현식, NOT NULL 등...)
-- 3. 제약조건 설정(PK, U, FK, CK, ....)
-- 4. 데이터 입력



SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'JOB_HISTORY';


SELECT *
FROM JOB_HISTORY;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'COUNTRIES';

SELECT *
FROM REGIONS;


SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'EMPLOYEES';

SELECT *
FROM JOB;

DESC JOBS;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'JOBS';


SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'COUNTRIES';

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'LOCATIONS';



SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'EMPLOYEES';

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'DEPARTMENTS';


SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'JOB_HISTORY';


SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'REGIONS';

