
--  [과목 테이블 생성 코드]
    CREATE TABLE SUBJECTS
    ( SUB_CODE VARCHAR2(20) 
    , SUB_NAME VARCHAR2(20)  CONSTRAINT SUB_NAME_NN NOT NULL
    , CONSTRAINT SUBJECTS_SUB_CODE_PK PRIMARY KEY(SUB_CODE)
    );
    --===>> Table SUBJECTS이(가) 생성되었습니다.

    DROP TABLE SUBJECTS;
    
    SELECT *
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TBL_출고';

    DESC TBL_출고;   

--  [과정 테이블 생성 코드]    
    CREATE TABLE COURSES
    ( CRS_CODE  VARCHAR2(20)    
    , CRS_NAME  VARCHAR2(20)    CONSTRAINT CRS_NAME_NN NOT NULL
    , CONSTRAINT COURSES_CRS_CODE_PK PRIMARY KEY(CRS_CODE)
    );
    --==>> Table COURSES이(가) 생성되었습니다.
    
--   [교수 테이블 생성 코드]    
    CREATE TABLE PROFESSORS
    ( PF_ID     VARCHAR2(20)    
    , PF_PW     VARCHAR2(20)    CONSTRAINT PF_PW_NN NOT NULL
    , PF_NAME   VARCHAR2(20)    CONSTRAINT PF_NAME_NN NOT NULL
    , PF_SSN    VARCHAR(14)     CONSTRAINT PF_SSN_NN NOT NULL
    , PF_DATE   DATE            DEFAULT SYSDATE
    , CONSTRAINT PROFESSORS_PF_ID_PK PRIMARY KEY(PF_ID)
    , CONSTRAINT PROFESSORS_PF_PW_UK CHECK (LENGTH(PF_PW) >= 7 AND LENGTH(PF_PW) <= 20)
    );
    --==>> Table PROFESSORS이(가) 생성되었습니다.

--  [학생 테이블 생성 코드] 
    CREATE TABLE STUDENTS
    ( ST_ID    VARCHAR2(20)
    , ST_PW    VARCHAR2(20) CONSTRAINT ST_PW_NN NOT NULL
    , ST_NAME  VARCHAR2(20) CONSTRAINT ST_NAME_NN NOT NULL
    , ST_SSN   VARCHAR(14)  CONSTRAINT ST_SSN_NN NOT NULL
    , ST_DATE  DATE         DEFAULT SYSDATE
    , CONSTRAINT STUDENTS_ST_ID_PK PRIMARY KEY(ST_ID)
    , CONSTRAINT STUDENTS_ST_PW_CK CHECK (LENGTH(ST_PW) >= 7 AND LENGTH(ST_PW) <= 20)
    );
    --==>> Table STUDENTS이(가) 생성되었습니다.   
            
--  [관리자 테이블 생성 코드]
    CREATE TABLE ADMINS
    ( AD_CODE   VARCHAR2(20)    
    , AD_ID     VARCHAR2(20)    
    , AD_PW     VARCHAR2(20)    CONSTRAINT AD_PW_NN NOT NULL
    , AD_DATE   DATE            DEFAULT SYSDATE
    , CONSTRAINT ADMINS_AD_CODE_PK PRIMARY KEY(AD_CODE)
    , CONSTRAINT ADMINS_AD_ID_UK   UNIQUE(AD_ID)
    , CONSTRAINT ADMINS_AD_PW_UK CHECK (LENGTH(AD_PW) >= 7 AND LENGTH(AD_PW) <= 20) 
    );
    --==>> Table ADMINS이(가) 생성되었습니다.
    
--  [교재 테이블 생성 코드]    
    CREATE TABLE BOOKS
    ( BK_CODE           VARCHAR2(20)
    , BK_NAME           VARCHAR2(20)    CONSTRAINT BOOKS_BK_NAME_NN NOT NULL
    , BK_PRICE          NUMBER(6)       CONSTRAINT BOOKS_BK_PRICE_NN NOT NULL
    , BK_EXPLANATION    VARCHAR2(100)
    , CONSTRAINT BOOKS_BK_CODE_PK PRIMARY KEY(BK_CODE)
    );
    --==>> Table BOOKS이(가) 생성되었습니다.
    
--  [중도탈락사유 테이블 생성 코드]    
    CREATE TABLE DROP_REASONS
    ( DO_REASON_CODE           VARCHAR2(20)
    , DO_REASON                VARCHAR2(50)     CONSTRAINT REASONS_DO_REASON_NN NOT NULL
    , CONSTRAINT REASON_DO_REASON_CODE_PK PRIMARY KEY(DO_REASON_CODE)
    );
    --==>> Table DROP_REASONS이(가) 생성되었습니다.
    
--  [강의실 테이블 생성 코드]        
   CREATE TABLE CLASSROOMS
    ( ROOM_CODE         VARCHAR2(20)
    , ROOM_NAME         VARCHAR2(20)  CONSTRAINT CLASSROOMS_NAME_NN NOT NULL
    , ROOM_EXPLANATION  VARCHAR2(100)
    , CONSTRAINT CLASSROOMS_CODE_PK PRIMARY KEY(ROOM_CODE)
    ); 
     --==>> Table CLASSROOMS이(가) 생성되었습니다.       

--------------------------------------------------------------------------------    
    
--  [개설과정 테이블 생성코드]    
    CREATE TABLE OPEN_COURSES
    ( OCRS_CODE         VARCHAR2(20)
    , CRS_CODE          VARCHAR2(20)
    , PF_ID             VARCHAR2(20)
    , ROOM_CODE         VARCHAR2(20)
    , START_DATE        DATE    CONSTRAINT COURSES_START_DATE_NN NOT NULL
    , END_DATE          DATE    CONSTRAINT COURSES_END_DATE_NN NOT NULL
    , CONSTRAINT OCRS_OCRS_CODE_PK PRIMARY KEY(OCRS_CODE)
    , CONSTRAINT OCRS_CRS_CODE_FK FOREIGN KEY(CRS_CODE) REFERENCES COURSES(CRS_CODE)
    , CONSTRAINT OCRS_PF_ID_FK FOREIGN KEY(PF_ID) REFERENCES PROFESSORS(PF_ID)
    , CONSTRAINT OCRS_ROOM_CODE_FK FOREIGN KEY(ROOM_CODE) REFERENCES CLASSROOMS(ROOM_CODE)
    );
    --==>> Table OPEN_COURSES이(가) 생성되었습니다. 

--  [수강신청 테이블 생성코드]   
    CREATE TABLE COURSE_REGISTRATIONS
    ( REG_CODE      VARCHAR2(20)
    , ST_ID         VARCHAR2(20)
    , OCRS_CODE     VARCHAR2(20)
    , REG_DATE      DATE        DEFAULT SYSDATE
    , CONSTRAINT COURSE_REG_REG_CODE_PK PRIMARY KEY(REG_CODE)
    
    , CONSTRAINT COURSE_REG_ST_ID_FK  FOREIGN KEY(ST_ID)
            REFERENCES STUDENTS(ST_ID)
            
    , CONSTRAINT COURSE_REG_OCRS_CODE_FK  FOREIGN KEY(OCRS_CODE)
            REFERENCES OPEN_COURSES(OCRS_CODE)
    );
    --==>> Table COURSE_REGISTRATIONS이(가) 생성되었습니다.
    
--  [중도탈락 테이블 생성코드]    
    CREATE TABLE DROP_OUT_LISTS
    ( DO_CODE           VARCHAR2(20)   
    , REG_CODE          VARCHAR2(20) 
    , DO_REASON_CODE    VARCHAR2(20) 
    , DO_DATE           DATE DEFAULT SYSDATE
    , CONSTRAINT DO_LISTS_DO_CODE_PK PRIMARY KEY(DO_CODE)
    , CONSTRAINT DO_LISTS_REG_CODE_FK FOREIGN KEY(REG_CODE)
                    REFERENCES COURSE_REGISTRATIONS(REG_CODE)
    , CONSTRAINT DO_LISTS_DO_REASON_CODE_FK FOREIGN KEY(DO_REASON_CODE)
                    REFERENCES DROP_REASONS(DO_REASON_CODE)
    );
    --==>> Table DROP_OUT_LISTS이(가) 생성되었습니다.
    
--  [개설과목 테이블 생성코드]    
    CREATE TABLE OPEN_SUBJECTS
    ( OSUB_CODE             VARCHAR(20)
    , OCRS_CODE             VARCHAR(20)
    , SUB_CODE              VARCHAR(20) 
    , BK_CODE               VARCHAR(20)
    , SUB_START_DATE        DATE        CONSTRAINT OPEN_SUBJECTS_SSD_NN NOT NULL
    , SUB_END_DATE          DATE        CONSTRAINT OPEN_SUBJECTS_SED_NN NOT NULL
    , ATTENDANCE_SCORE      NUMBER(3)   CONSTRAINT OPEN_SUBJECTS_AS_NN NOT NULL
    , WRITTEN_SCORE         NUMBER(3)   CONSTRAINT OPEN_SUBJECTS_WS_NN NOT NULL
    , PRACTICAL_SCORE       NUMBER(3)   CONSTRAINT OPEN_SUBJECTS_PS_NN NOT NULL
    , CONSTRAINT OPEN_SUBJECTS_OSUB_CODE_PK PRIMARY KEY(OSUB_CODE)
    , CONSTRAINT ATTENDANCE_SCORE CHECK(ATTENDANCE_SCORE BETWEEN 0 AND 100)
    , CONSTRAINT WRITTEN_SCORE CHECK(WRITTEN_SCORE BETWEEN 0 AND 100)
    , CONSTRAINT PRACTICAL_SCORE CHECK(PRACTICAL_SCORE BETWEEN 0 AND 100)
    , CONSTRAINT OCRS_CODE_FK FOREIGN KEY(OCRS_CODE) REFERENCES OPEN_COURSES(OCRS_CODE)
    , CONSTRAINT SUB_CODE_FK FOREIGN KEY(SUB_CODE) REFERENCES SUBJECTS(SUB_CODE)
    , CONSTRAINT BK_CODE_FK FOREIGN KEY(BK_CODE) REFERENCES BOOKS(BK_CODE)
    );
    --==>> Table OPEN_SUBJECTS이(가) 생성되었습니다.
    
--  [성적 테이블 생성코드]       
    CREATE TABLE SCORES
    ( SCORE_CODE            VARCHAR2(20)
    , REG_CODE              VARCHAR2(20)
    , OSUB_CODE             VARCHAR2(20)
    , ATTENDANCE_SCORE      NUMBER(3)   CONSTRAINT ATTENDANCE_SCORE_NN NOT NULL
    , WRITTEN_SCORE         NUMBER(3)   CONSTRAINT WRITTEN_SCORE_NN NOT NULL
    , PRACTICAL_SCORE       NUMBER(3)   CONSTRAINT PRACTICAL_SCORE_NN NOT NULL
    , TEAT_DATE             DATE        CONSTRAINT TEST_DATE_NN NOT NULL
    , CONSTRAINT SCORES_SCORE_CODE_PK PRIMARY KEY(SCORE_CODE)
    , CONSTRAINT SCORES_REG_CODE_FK FOREIGN KEY(REG_CODE)
                 REFERENCES COURSE_REGISTRATIONS(REG_CODE)
    , CONSTRAINT SCORES_OSUB_CODE_FK FOREIGN KEY(OSUB_CODE)
                 REFERENCES OPEN_SUBJECTS(OSUB_CODE)
    , CONSTRAINT SCORES_ATTENDANCE_SCORE_CK CHECK (ATTENDANCE_SCORE BETWEEN 0 AND 100)
    , CONSTRAINT SCORES_WRITTEN_SCORE_CK CHECK (WRITTEN_SCORE BETWEEN 0 AND 100)
    , CONSTRAINT SCORES_PRACTICAL_SCORE_CK CHECK (PRACTICAL_SCORE BETWEEN 0 AND 100)
    );
    --==>> Table SCORES이(가) 생성되었습니다.
    